# Generated by Django 3.1.5 on 2021-01-18 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreated', models.TimeField(auto_now_add=True, verbose_name='Date created')),
                ('UserName', models.CharField(max_length=32, verbose_name='Username')),
                ('UserLink', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='UserAccountLink')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.CharField(max_length=64, verbose_name='Header')),
                ('Description', models.TextField(verbose_name='Description')),
                ('AccountLink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.account', verbose_name='ToDoListAccountLink')),
            ],
            options={
                'verbose_name': 'ToDo List',
                'verbose_name_plural': 'ToDo Lists',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Finished', models.BooleanField(default=False, verbose_name='Finished?')),
                ('TimeAdded', models.TimeField(auto_now_add=True, verbose_name='Time added')),
                ('Label', models.CharField(max_length=32, verbose_name='Label')),
                ('Description', models.TextField(verbose_name='Description')),
                ('ImageURL', models.URLField(verbose_name='ImageURL')),
                ('ToDoListLink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.todolist', verbose_name='ToDoListTaskLink')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IconURL', models.URLField(verbose_name='IconURL')),
                ('Label', models.CharField(max_length=32, verbose_name='Label')),
                ('TagTaskLink', models.ManyToManyField(to='todolist.Task', verbose_name='TagTaskLink')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
