# Generated by Django 3.1.5 on 2021-01-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='TagTaskLink',
        ),
        migrations.AddField(
            model_name='task',
            name='TagTaskLink',
            field=models.ManyToManyField(to='todolist.Tag', verbose_name='TagTaskLink'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='Label',
            field=models.CharField(blank=True, max_length=32, verbose_name='Label'),
        ),
    ]
