# Generated by Django 3.1.5 on 2021-01-19 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20210119_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Finished',
            field=models.BooleanField(blank=True, default=False, verbose_name='Finished?'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ImageURL',
            field=models.URLField(blank=True, verbose_name='ImageURL'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Label',
            field=models.CharField(blank=True, max_length=32, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='task',
            name='TagTaskLink',
            field=models.ManyToManyField(blank=True, to='todolist.Tag', verbose_name='TagTaskLink'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ToDoListLink',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='todolist.todolist', verbose_name='ToDoListTaskLink'),
        ),
    ]
